-- ===========================================================================
-- ARANCEL VENEZUELA MASTER - ORACLE DATABASE VERSION (DDL)
-- ===========================================================================

-- Drop tables if they exist
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE subpartida_regimen CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE notas_legales CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE subpartidas CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE partidas CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE capitulos CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE secciones CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE regimen_legal_catalogo CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Create tables using standard Oracle syntax
CREATE TABLE secciones (
    id_seccion  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(50) NOT NULL,
    descripcion VARCHAR2(1000)
);

CREATE TABLE capitulos (
    id_capitulo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_seccion  NUMBER REFERENCES secciones(id_seccion) ON DELETE CASCADE,
    numero      VARCHAR2(10) NOT NULL,
    descripcion VARCHAR2(1000)
);

CREATE TABLE partidas (
    id_partida  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_capitulo NUMBER REFERENCES capitulos(id_capitulo) ON DELETE CASCADE,
    codigo      VARCHAR2(20) NOT NULL,
    descripcion VARCHAR2(2000)
);

CREATE TABLE subpartidas (
    id_subpartida NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_partida    NUMBER REFERENCES partidas(id_partida) ON DELETE CASCADE,
    codigo        VARCHAR2(20) NOT NULL,
    descripcion   CLOB, -- CLOB for very long nested description text
    aec           VARCHAR2(50),
    ex_aec        VARCHAR2(50),
    unidad        VARCHAR2(50)
);

CREATE TABLE regimen_legal_catalogo (
    id_regimen   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo       VARCHAR2(50) NOT NULL,
    descripcion  VARCHAR2(1000)
);

CREATE TABLE subpartida_regimen (
    id_subpartida NUMBER REFERENCES subpartidas(id_subpartida) ON DELETE CASCADE,
    id_regimen    NUMBER REFERENCES regimen_legal_catalogo(id_regimen) ON DELETE CASCADE,
    tipo          VARCHAR2(10),
    PRIMARY KEY (id_subpartida, id_regimen)
);

CREATE TABLE notas_legales (
    id_nota     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_seccion  NUMBER REFERENCES secciones(id_seccion) ON DELETE CASCADE,
    id_capitulo NUMBER REFERENCES capitulos(id_capitulo) ON DELETE CASCADE,
    texto       CLOB -- CLOB for legal text paragraphs
);

COMMENT ON TABLE secciones IS 'Secciones arancelarias del arancel de aduanas';
COMMENT ON TABLE capitulos IS 'Capitulos pertenecientes a cada seccion arancelaria';
COMMENT ON TABLE partidas IS 'Partidas arancelarias a 4 digitos';
COMMENT ON TABLE subpartidas IS 'Subpartidas arancelarias a nivel nacional de 10 digitos';
